services:
    nginx:
        build: ./requirements/nginx/
        container_name: nginx
        restart: on-failure
        volumes:
            - wordpress:/var/www/html
        networks:
            - webnet
        ports:
            - "8080:8080"
        depends_on:
            - wordpress
    wordpress:
        build: ./requirements/wordpress/
        container_name: wordpress
        restart: on-failure
        volumes:
            - wordpress:/var/www/html
        networks:
            - webnet
            - dbnet
        ports:
          - "9000:9000"
        depends_on:
            - mariadb
    mariadb:
        build: ./requirements/mariadb/
        container_name: mariadb
        restart: on-failure
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - dbnet
        ports:
            - "3306:3306"

volumes:
    wordpress:
         driver: local
         driver_opts:
            type: none
            device: ./requirements/wordpress/volume/
            o: bind
    mariadb:
         driver: local
         driver_opts:
            type: none
            device: ./requirements/mariadb/volume/
            o: bind

networks:
    webnet:
        driver: bridge
    dbnet:
        driver: bridge