services:
    nginx:
        build: ./requirements/nginx/
        container_name: nginx
        restart: on-failure
        volumes:
            - ./requirements/wordpress/volume/:/var/www/html
        networks:
            - webnet
        ports:
            - "8080:8080"
        depends_on:
            - wordpress
    wordpress:
        build: ./requirements/wordpress/
        container_name: wordpress
        restart: on-failure
        volumes:
            - ./requirements/wordpress/volume/:/var/www/html
        networks:
            - webnet
            - dbnet
        depends_on:
            - mariadb
        env_file:
            - ../secrets/.env
    mariadb:
        build: ./requirements/mariadb/
        container_name: mariadb
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./requirements/mariadb/volume/:/var/lib/mysql
        networks:
            - dbnet
        env_file:
            - ../secrets/.env

networks:
    webnet:
        driver: bridge
    dbnet:
        driver: bridge