services:
    nginx:
        build: ./requirements/nginx/
        container_name: nginx
        restart: on-failure
        volumes:
            - wordpress:/var/www/html
        networks:
            - webnet
        ports:
            - "8080:8080"
        depends_on:
            - wordpress
    wordpress:
        build: ./requirements/wordpress/
        container_name: wordpress
        restart: on-failure
        volumes:
            - wordpress:/var/www/html
        networks:
            - webnet
            - dbnet
        depends_on:
            - mariadb
        env_file:
            - ../secrets/.env
    mariadb:
        build: ./requirements/mariadb/
        container_name: mariadb
        restart: on-failure
        volumes:
            - ./requirements/mariadb/volume/:/var/lib/mysql
        networks:
            - dbnet
        env_file:
            - ../secrets/.env

volumes:
    wordpress:
         driver: local
         driver_opts:
            type: none
            device: ./requirements/wordpress/volume/
            o: bind

networks:
    webnet:
        driver: bridge
    dbnet:
        driver: bridge